name: GitHub Actions Secret Example

on:
  push:
    branches: [ main ]


jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Echo out a Github Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked: "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret: "
          echo ${{ secrets.SECRET_TOKEN }} | sed 's/./&/ g'
