# This is a basic workflow to help you get started with Actions

name: Getting Started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build-on-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checks-out your repository
        uses: actions/checkout@v3

      # Step 2 - Runs a single command using the runners shell
      - name: Step 2 - Run a one-line script
        run: echo Hello, world!

      # Step 3 - Runs a set of commands using the runners shell
      - name: Step 3 - Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Step 4 - Pom xml
      - name : Step 4 - Pom xml
        run : sh ./github-actions-script.sh

      # Step 5 - 10 most important commands when starting
      - name : Step 5 - Runs 10 sub commands
        run : mvn -B package --file pom.xml

      - name: Step 6 - List Ubuntu Environment Variables
        run: env
          
          
          
